### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by mjmadhur** [sijan8s3/MVVM-News-App#2]
Can i add a read me for ur app

**Comment by sijan8s3** [comment]
sure, go for it!
please make sure it's worth a PR! :)

**Comment by sijan8s3** [comment]
> Can i add a read me for ur app

**Comment by mjmadhur** [comment]
A readme with screenshots of app would be good!??

**Comment by sijan8s3** [comment]
Sounds great,
Also, quality description would be wonderful.

**Comment by mjmadhur** [comment]
Okkk
